spring:
  config:
    import:
      - optional:aws-secretsmanager:/prod/application/twilio/credentials?prefix=twilio.
      - optional:aws-secretsmanager:/prod/database/credentials?prefix=database.
      -
  datasource:
    url: REPLACE_ME
    username: ${database.username}
    password: ${database.password}

springdoc:
  api-docs:
    enabled: true