spring:
  config:
    import:
      - optional:aws-secretsmanager:/prod/application/twilio/credentials?prefix=twilio.
      - optional:aws-secretsmanager:/prod/database/credentials?prefix=database.
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    url: jdbc:sqlserver://theseasonneverendswl-prod.c4uijqbxxtmv.us-east-2.rds.amazonaws.com:1433;databaseName=TSNE_WL;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.rds.amazonaws.com
    username: ${database.username}
    password: ${database.password}

springdoc:
  api-docs:
    enabled: false

twilio:
  account:
    sid: account-sid
    auth-token: auth-token
  sendgrid:
    fromEmail: ${twilio.sgSourceEmail}
    sgApikey: ${twilio.sgApiKey}