spring:
  config:
    import:
      - optional:aws-secretsmanager:/prod/application/twilio/credentials?prefix=twilio.
#      - optional:aws-secretsmanager:/prod/database/credentials?prefix=database.
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    url: REPLACE_ME
    username: ${database.username}
    password: ${database.password}

springdoc:
  api-docs:
    enabled: false

twilio:
  account:
    sid: account-sid
    auth-token: auth-token
  sendgrid:
    fromEmail: ${twilio.sgSourceEmail}
    sgApikey: ${twilio.sgApiKey}